### ISSUE TITLE
[1.18.1, v1.4.3 hotfix] Opal ore generation in config resets to false

### ISSUE THREAD

**Issue by mbrozzo** [LimeAppleBoat/EndGoblinTraders#10]
The config option to generate opal ore is set to false each time I restart the game.

**Comment by Jab125** [comment]
Opal ore gen will arrive in v1.5, 1.4.3 only patched Void Totem Compat

There is no Opal ore gen in the code in 1.4.3 which is why it is disabled.

And it being on in 1.4.2-1.4.3 will not actually change anything.

**Comment by mbrozzo** [comment]
Oh I'm sorry, seeing the option there I supposed it was available
