### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by kittech0** [LimeAppleBoat/EndGoblinTraders#11]
My game crashes
[latest.log](https://github.com/LimeAppleBoat/EndGoblinTraders/files/8188293/latest.log)
1.18.1, latest version of fabric loader and fabric api

**Comment by recon88** [comment]
Can confirm. Crashes on Fabric Loader 0.13.3 with the latest Fabric API update 0.46.6

**Comment by Jab125** [comment]
will fix tommorow

**Comment by Jab125** [comment]
kinda delayed, but seems to work on latest fabric api version and 1.18.2

**Comment by kittech0** [comment]
> kinda delayed, but seems to work on latest fabric api version and 1.18.2

becuz that version is for 1.18.2 bruh, there was too big update between 1.18.1 and 1.18.2 to mods work

**Comment by Jab125** [comment]
Try 1.4.4 for 1.17, 1.17.1, 1.18 and 1.18.1
