### ISSUE TITLE
Game crashes when spawning an end goblin trader

### ISSUE THREAD

**Issue by Xfrtrex** [LimeAppleBoat/EndGoblinTraders#14]
maybe this is a mod compatibility issue?

---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 5/27/22, 2:09 PM
Description: Exception ticking world

java.lang.NoSuchMethodError: 'boolean net.minecraft.class_2874.method_31108(net.minecraft.class_2874)'
	at com.jab125.egt.EGobT.lambda$onInitialize$2(EGobT.java:63)
	at com.jab125.limeappleboat.gobt.api.GobTEvents.lambda$static$2(GobTEvents.java:27)
	at net.hat.gt.spawning.GoblinTraderSpawner.spawnTrader(GoblinTraderSpawner.java:126)
	at net.hat.gt.spawning.GoblinTraderSpawner.tick(GoblinTraderSpawner.java:91)
	at net.hat.gt.spawning.SpawnHandler$OnWorldTick.onEndTick(SpawnHandler.java:59)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$10(ServerTickEvents.java:66)
	at org.quiltmc.qsl.lifecycle.api.event.ServerWorldTickEvents.lambda$static$2(ServerWorldTickEvents.java:48)
	at net.minecraft.class_3218.handler$deb001$endServerTick(class_3218.java:10166)
	at net.minecraft.class_3218.method_18765(class_3218.java:374)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:907)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851)
	at net.minecraft.class_1132.method_3748(class_1132.java:97)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
	at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.jab125.egt.EGobT.lambda$onInitialize$2(EGobT.java:63)
	at com.jab125.limeappleboat.gobt.api.GobTEvents.lambda$static$2(GobTEvents.java:27)
	at net.hat.gt.spawning.GoblinTraderSpawner.spawnTrader(GoblinTraderSpawner.java:126)
	at net.hat.gt.spawning.GoblinTraderSpawner.tick(GoblinTraderSpawner.java:91)
	at net.hat.gt.spawning.SpawnHandler$OnWorldTick.onEndTick(SpawnHandler.java:59)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$10(ServerTickEvents.java:66)
	at org.quiltmc.qsl.lifecycle.api.event.ServerWorldTickEvents.lambda$static$2(ServerWorldTickEvents.java:48)
	at net.minecraft.class_3218.handler$deb001$endServerTick(class_3218.java:10166)
	at net.minecraft.class_3218.method_18765(class_3218.java:374)

-- Affected level --
Details:
	All players: 1 total; [class_3222['Xfrtrex'/209, l='ServerLevel[New World]', x=201.83, y=69.75, z=-102.70]]
	Chunk stats: 3909
	Level dimension: minecraft:overworld
	Level spawn location: World: (16,69,-48), Section: (at 0,5,0 in 1,4,-3; chunk contains blocks 16,-64,-48 to 31,319,-33), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 662118 game time, 121128 day time
	Level name: New World
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
	Level weather: Rain time: 3360 (now: false), thunder time: 191 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:907)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851)
	at net.minecraft.class_1132.method_3748(class_1132.java:97)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 700652144 bytes (668 MiB) / 2684354560 bytes (2560 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 5
	Microarchitecture: unknown
	Frequency (GHz): 3.79
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 2060 SUPER
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1f06
	Graphics card #0 versionInfo: DriverVersion=30.0.15.1259
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 35757.46
	Virtual memory used (MB): 23625.99
	Swap memory total (MB): 19456.00
	Swap memory used (MB): 1453.41
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		adventurez: AdventureZ 1.4.10
		animatica: Animatica 0.4+1.18
		architectury: Architectury 4.4.61
		axolotlitemfix: Axolotl Item Fix 1.1.3
		badpackets: Bad Packets 0.1.2
		bclib: BCLib 1.4.6
		betterend: Better End 1.1.0
		bookshelf: Bookshelf 13.0.13
		boostedbrightness: Boosted Brightness 2.1.1
		cameraoverhaul: Camera Overhaul 1.3.0-fabric-universal
		capybara: Capybara 1.0.4
		chat_heads: Chat Heads 0.6.0
		clickadv: Clickable Advancements Mod 2.6
		cloth-config: Cloth Config v6 6.2.62
			cloth-basic-math: cloth-basic-math 0.6.1
		crafttweaker: CraftTweaker 9.1.140
			org_javassist_javassist: javassist 3.28.0-GA
			org_reflections_reflections: reflections 0.10.2
		crawl: Crawl 0.10.6
			mm: Manningham Mills 2.3
		croptopia: Croptopia 2.0.0
			com_typesafe_config: config 1.4.1
			io_leangen_geantyref_geantyref: geantyref 1.3.11
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		darkpaintings: DarkPaintings 10.0.1
		deepslatecutting: Deepslate Cutting 1.3.3
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
			maybe-data: Maybe data 1.3.1-1.18.2
		eatinganimationid: Eating Animation 1.6
		edenring: EdenRing 0.5.1
		enchdesc: EnchantmentDescriptions 10.0.3
		endgoblintraders: End Goblin Traders 1.4.4
		fabric: Fabric API 0.53.4+1.18.2
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.1+2373a54560
			fabric-biome-api-v1: Fabric Biome API (v1) 8.0.4+7b0f312660
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.12+3ac43d9560
			fabric-command-api-v1: Fabric Command API (v1) 1.1.9+d7c144a860
			fabric-commands-v0: Fabric Commands (v0) 0.2.8+b4f4f6cd60
			fabric-containers-v0: Fabric Containers (v0) 0.1.21+d7c144a860
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.0.5+d82b939260
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.1+474e4f7960
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.1+ee261a3e60
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.19+ffb2c71e60
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.8+d7c144a860
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.19+d7c144a860
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.16+d7c144a860
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
			fabric-item-api-v1: Fabric Item API (v1) 1.5.0+85719ab760
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.12+91896a4960
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.12+54e5b2ec60
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.10+b4f4f6cd60
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.11+d7c144a860
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.1+81ea5b3c60
			fabric-models-v0: Fabric Models (v0) 0.3.6+d7c144a860
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.21+d882b91560
			fabric-networking-v0: Fabric Networking (v0) 0.3.8+b4f4f6cd60
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.1.1+032c981d60
			fabric-particles-v1: Fabric Particles (v1) 0.2.12+526dc1ac60
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.8+0d9ab37260
			fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.13+d882b91560
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.5.0+7faf0d8860
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.11+b4f4f6cd60
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.7+d7c144a860
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.2+54e5b2ec60
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.13+b4f4f6cd60
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.7+54e5b2ec60
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.3+91b7aa6660
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.10+d882b91560
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.0+1f6558e860
			fabric-textures-v0: Fabric Textures (v0) 1.0.12+3ac43d9560
			fabric-transfer-api-v1: Fabric Transfer API (v1) 1.6.2+f4563ac860
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.0.0+bd8a4a1860
		fabricloader: Fabric Loader 0.14.6
		feature_nbt_deadlock_be_gone: Feature NBT Deadlock Be Gone - Fabric 2.0.0+1.18.2-rc1
		ftblibrary: FTB Library 1802.3.6-build.119
		ftbquests: FTB Quests 1802.3.8-build.101
		ftbteams: FTB Teams 1802.2.6-build.51
		geckolib3: Geckolib 3.0.42
			com_eliotlash_mclib_mclib: mclib 18
			com_eliotlash_molang_molang: molang 18
		geodes: More Geodes 1.4.2
		goblintraders: Goblin Traders 1.5.1
		illuminations: Illuminations 1.10.4
		indium: Indium 1.0.3+mc1.18.2
		infusion_table: Infusion Table 1.0.5
		ingredient-extension-api: Ingredient Extension API 2.0.5
		inmis: Inmis 2.6.0-1.18.2
			omega-config: OmegaConfig 1.2.3-1.18.1
		iris: Iris 1.2.5-pbr-beta.4
			org_anarres_jcpp: jcpp 1.4.14
		itemfilters: Item Filters 1802.2.7-build.21
		java: OpenJDK 64-Bit Server VM 17
		krypton: Krypton 0.1.9
			com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		lazydfu: LazyDFU 0.1.2
		lithium: Lithium 0.7.10
		mavm: More Axolotl Variants Mod 1.0.7a
		mca: Minecraft Comes Alive 7.2.1+1.18.2
		minecraft: Minecraft 1.18.2
		moborigins: Mob Origins 1.8.1
		mobscarecrow: Mob Scarecrow 1.2.2
		modmenu: Mod Menu 3.2.2
		more-axolotls: More Axolotls 1.0.2
		morevillagers-fabric: MoreVillagersFabric 3.2.0-SNAPSHOT
		naturescompass: Nature's Compass 1.18.2-2.0.3-fabric
		okzoomer: Ok Zoomer 5.0.0-beta.4+1.18.2
			libzoomer: LibZoomer 0.4.0+1.18.2
			org_quiltmc_quilt-json5: quilt-json5 1.0.0
			quilt_tags: Quilt Tags API 1.0.0+1.18.2-SNAPSHOT
			quilted-fabric-api-base: Quilted Fabric API Base 1.0.0+1.18.2-SNAPSHOT
				quilt_base: Quilt Base API 1.0.0+1.18.2-SNAPSHOT
			quilted-fabric-lifecycle-events-v1: Quilted Fabric Lifecycle Events (v1) 2.0.1+1.18.2-SNAPSHOT
				quilt_lifecycle_events: Quilt Lifecycle Events 1.0.0+1.18.2-SNAPSHOT
			quilted-fabric-resource-loader-v0: Quilted Fabric Resource Loader (v0) 1.0.1+1.18.2-SNAPSHOT
				quilt_resource_loader: Quilt Resource Loader 1.0.0+1.18.2-SNAPSHOT
			spruceui: SpruceUI 3.3.2+1.17
		origins: Origins 1.4.1
			apoli: Apoli 2.3.3
				additionalentityattributes: Additionalentityattributes 1.0.0+1.18.2
				calio: Calio 1.5.1
				cardinal-components-base: Cardinal Components API (base) 4.1.4
				cardinal-components-entity: Cardinal Components API (entities) 4.1.4
				playerabilitylib: Pal 1.5.0
			reach-entity-attributes: Reach Entity Attributes 2.1.1
		origins-classes: Origins: Classes 1.3.0
		oxidized: Oxidized 1.6.4
		patchouli: Patchouli 1.18.2-67-FABRIC
			fiber: fiber 0.23.0-2
		pehkui: Pehkui 3.3.1+1.14.4-1.19
			kanos_config: Kanos Config 0.3.1+1.14.4-1.19
		repurposed_structures: Repurposed Structures 4.1.9+1.18.2
		roughlyenoughitems: Roughly Enough Items 8.2.463
		simple-rpc: Simple RPC 3.0.1
			me_hypherionmc_simple-rpc-common: simple-rpc-common 3.0.1
		skinlayers: 3d Skin Layers 1.4.4-mc1.18.2
		sodium: Sodium 0.4.1+build.15
			org_joml_joml: joml 1.10.2
		the_bumblezone: The Bumblezone - Fabric 5.0.14+1.18.2
			fake-player-api: Fake Player API 0.3.0
		thonkutil: ThonkUtil 2.14.1+1.18
			thonkutil-base: ThonkUtil Base 1.12.2+23c1dc2c60
			thonkutil-capes-v1: ThonkUtil Capes (v1) 1.3.2+9e23427060
			thonkutil-coords-v1: ThonkUtil Coords (v1) 1.0.19+9b80223760
			thonkutil-customization-v1: ThonkUtil Customization (v1) 1.0.14+9b80223760
			thonkutil-legacy: ThonkUtil Legacy 1.0.20+9b80223760
			thonkutil-modchecker-v1: ThonkUtil ModChecker (v1) 1.0.12+9b80223760
			thonkutil-potions-v0: ThonkUtil Potions (v0) 1.4.1+9b80223760
			thonkutil-titlescreen-v1: ThonkUtil TitleScreen (v1) 1.1.9+9b80223760
			thonkutil-trades-v1: ThonkUtil Trades (v1) 1.1.20+9b80223760
		trinkets: Trinkets 3.3.1
		voidz: VoidZ 1.0.7
		waystones: Waystones 2.5.3
		wthit: wthit 4.10.3
		xaerominimap: Xaero's Minimap 22.8.2
		xaeroworldmap: Xaero's World Map 1.22.0
		yigd: You're in Grave Danger 1.3.5
	Loaded Shaderpack: (off)
	Server Running: true
	Player Count: 1 / 8; [class_3222['Xfrtrex'/209, l='ServerLevel[New World]', x=201.83, y=69.75, z=-102.70]]
	Data Packs: vanilla
	World Generation: Experimental
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\XfrPl\AppData\Roaming\.minecraft\crash-reports\crash-2022-05-27_14.09.17-server.txt
AL lib: (EE) alc_cleanup: 1 device not closed
14:09:19.399
Process crashed with exit code -1

**Comment by Jab125** [comment]
End Goblin Traders 1.4.1 is for 1.17 & 1.18 & 1.18.1, not 1.18.2
Use the 1.5 Beta https://www.curseforge.com/minecraft/mc-mods/end-goblin-traders-fabric/files/3755077 which supports Minecraft 1.18.2
