### ISSUE TITLE
Unable to load model: 'endgoblintraders:mystery_item#inventory'

### ISSUE THREAD

**Issue by ghost** [LimeAppleBoat/EndGoblinTraders#19]
when i start minecraft i get this error

Unable to load model: 'endgoblintraders:mystery_item#inventory' referenced from: endgoblintraders:mystery_item#inventory: java.io.FileNotFoundException: endgoblintraders:models/item/mystery_item.json

i use 
end-goblin-traders-1.5.1
goblin-traders-1.5.2
minecraft 1.19.2
fabric .14.10
fabric-api-0.68.0+1.19.2
cloth-config-8.2.88-fabric

**Comment by Jab125** [comment]
does not matter, it doesn't affect anything
