### ISSUE TITLE
1.18 Crash Report for EndGoblinTraders 1.4.1

### ISSUE THREAD

**Issue by RubyRezal** [LimeAppleBoat/EndGoblinTraders#4]
[crash-2021-11-30_23.48.08-server.txt](https://github.com/LimeAppleBoat/EndGoblinTraders/files/7630930/crash-2021-11-30_23.48.08-server.txt)

**Comment by SuryaRajgor** [comment]
[latest.log](https://github.com/LimeAppleBoat/EndGoblinTraders/files/7631040/latest.log)


1.4.1 Hotfix

**Comment by Jab125** [comment]
"fixed" in 1.4.2 by removing the ore gen

**Comment by RubyRezal** [comment]
If the opal ore has been removed, shouldn't the opal trades be disabled? At least until the ore generation is fixed?

**Comment by JosephYapYEEEEEEEEEEEEEEEEEEEEEEEEEEEET** [comment]
you can still obtain opal by trading
