### ISSUE TITLE
Trading for Opals without ore generation appears to be nearly impossible

### ISSUE THREAD

**Issue by RubyRezal** [LimeAppleBoat/EndGoblinTraders#7]
you can still obtain opal by trading

_Originally posted by @JosephYapYEEEEEEEEEEEEEEEEEEEEEEEEEEEET in https://github.com/LimeAppleBoat/EndGoblinTraders/issues/4#issuecomment-984126285_

My server has been running End Goblin Traders for about a month and we have yet to see a viable trade for obtaining opals.  The Wiki says we should be able to trade "15 gold for 1 opal" but no such trade is ever offered.

We only ever see 1 Instant Health III potion for 1 opal.  I finally found out the Instant Health III potion is a rare trade from Vein Goblins by spamming spawn eggs for them in creative.  Nobody on my server has seen this trade yet in survival.

Environment:
Minecraft 1.18.1
Fabric 0.12.12
Goblin Traders 1.4.1
End Goblin Traders 1.4.2

**Comment by Jab125** [comment]
<img width="966" alt="Screen Shot 2022-01-07 at 5 36 41 pm" src="https://user-images.githubusercontent.com/67534807/148502572-3e189b42-1d0d-4951-8865-5c66753cdd85.png">
I've re-enabled ore generation, i'll be replacing the 15 gold for 1 opal with 2 netherite ingots for 1 opal

**Comment by Jab125** [comment]
@RubyRezal it will be in 1.5, not 1.4.3 (1.4.3 is fixing a mod compat bug)
