### ISSUE TITLE
Conflict with Void Totem (Fabric) | 1.18.1

### ISSUE THREAD

**Issue by ghost** [LimeAppleBoat/EndGoblinTraders#8]
MC version: 1.18.1
Fabric version: 0.12.12

Mods used (ignoring dependencies):
End Goblin Traders (Fabric) v1.4.2
Void Totem (Fabric) v1.1.0

Issue: While having EGT installed along side VT, VT's totem of void undying does not have it's effect. Instead of preventing death by void, it just lets it happen. Most likely related to the extra totem item added in by the mod if I had to guess.

**Comment by Jab125** [comment]
@switchnlade can you get the artifacts from https://github.com/LimeAppleBoat/EndGoblinTraders/actions/runs/1798997611
when you download the artifacts, use the one that is not like 1.5-dev or 1.5-sources/sources-dev
check if its fixed.

**Comment by ghost** [comment]
With 1.5, everything works as intended. Thank you for fixing it up!
